fix: Change coverage badge fix

diff --git a/.github/workflows/chores.yml b/.github/workflows/chores.yml
--- a/.github/workflows/chores.yml
+++ b/.github/workflows/chores.yml
@@ -218,9 +218,12 @@ jobs:
   coverage-badge:
     name: Update coverage badge on README
     runs-on: ubuntu-latest
-    needs: [test]
+    needs: [ test ]
     if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     steps:
+      - name: Checkout repository  # Ensures README.md is available
+        uses: actions/checkout@v4
+
       - name: Download coverage artifact
         uses: actions/download-artifact@v4
         with:
@@ -229,6 +232,9 @@ jobs:
 
       - name: List downloaded files (debugging)
         run: ls -R
+
+      - name: Verify README exists
+        run: ls -l README.md || echo "README.md not found!"
 
       - name: Generate Go Coverage Badge
         id: generate-badge
@@ -257,6 +263,7 @@ jobs:
           git config --local user.name "GitHub Action"
           git add README.md
           git commit -m "chore: Updated coverage badge."
+          git push origin main
 
 
   capture-coverage:
